// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuEjLNdUAqZiYmn4rwyK0VwKHFG6my_Rs',
    appId: '1:730640135992:web:eb7d889ee33f5bf18533cd',
    messagingSenderId: '730640135992',
    projectId: 'motoguzziclub-97318',
    authDomain: 'motoguzziclub-97318.firebaseapp.com',
    storageBucket: 'motoguzziclub-97318.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD105epIl0M1NC2XKk4MgH-g8-mSVzRuBQ',
    appId: '1:730640135992:android:c2f0949ac6d9811f8533cd',
    messagingSenderId: '730640135992',
    projectId: 'motoguzziclub-97318',
    storageBucket: 'motoguzziclub-97318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLp38KHLXFEOpcS0xINyJrApErxuzRcuc',
    appId: '1:730640135992:ios:5f74271c72a116b88533cd',
    messagingSenderId: '730640135992',
    projectId: 'motoguzziclub-97318',
    storageBucket: 'motoguzziclub-97318.firebasestorage.app',
    iosBundleId: 'com.example.motoGuzziClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLp38KHLXFEOpcS0xINyJrApErxuzRcuc',
    appId: '1:730640135992:ios:5f74271c72a116b88533cd',
    messagingSenderId: '730640135992',
    projectId: 'motoguzziclub-97318',
    storageBucket: 'motoguzziclub-97318.firebasestorage.app',
    iosBundleId: 'com.example.motoGuzziClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuEjLNdUAqZiYmn4rwyK0VwKHFG6my_Rs',
    appId: '1:730640135992:web:5ea2e5e208c0ec278533cd',
    messagingSenderId: '730640135992',
    projectId: 'motoguzziclub-97318',
    authDomain: 'motoguzziclub-97318.firebaseapp.com',
    storageBucket: 'motoguzziclub-97318.firebasestorage.app',
  );
}
